# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(900, 1100)
        mainWindow.setMinimumSize(QtCore.QSize(900, 1100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        mainWindow.setFont(font)
        mainWindow.setIconSize(QtCore.QSize(40, 40))
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 930, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 930, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(30, 930, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 11, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_1.setObjectName("label_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 930, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 70, 831, 831))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 100,100);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.dateEdit_1 = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dateEdit_1.setFont(font)
        self.dateEdit_1.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit_1.setObjectName("dateEdit_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.comboBox_1 = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setEditable(True)
        self.comboBox_1.setObjectName("comboBox_1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_1)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_1.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_1.setStyleSheet("color: rgb(155, 10, 10);")
        self.lineEdit_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 930, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action11 = QtWidgets.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("hetong2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action11.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action11.setFont(font)
        self.action11.setObjectName("action11")
        self.action12 = QtWidgets.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("zijin1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action12.setIcon(icon1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.action12.setFont(font)
        self.action12.setObjectName("action12")
        self.action13 = QtWidgets.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Present.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action13.setIcon(icon2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action13.setFont(font)
        self.action13.setObjectName("action13")
        self.action14 = QtWidgets.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("wuliu2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action14.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action14.setFont(font)
        self.action14.setObjectName("action14")
        self.action15 = QtWidgets.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("wuliu3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action15.setIcon(icon4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action15.setFont(font)
        self.action15.setObjectName("action15")
        self.action16 = QtWidgets.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ouster.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action16.setIcon(icon5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action16.setFont(font)
        self.action16.setObjectName("action16")
        self.action17 = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("hezuohuoban2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action17.setIcon(icon6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action17.setFont(font)
        self.action17.setObjectName("action17")
        self.action21 = QtWidgets.QAction(mainWindow)
        self.action21.setObjectName("action21")
        self.action22 = QtWidgets.QAction(mainWindow)
        self.action22.setObjectName("action22")
        self.action23 = QtWidgets.QAction(mainWindow)
        self.action23.setObjectName("action23")
        self.action24 = QtWidgets.QAction(mainWindow)
        self.action24.setObjectName("action24")
        self.action25 = QtWidgets.QAction(mainWindow)
        self.action25.setObjectName("action25")
        self.action26 = QtWidgets.QAction(mainWindow)
        self.action26.setObjectName("action26")
        self.action31 = QtWidgets.QAction(mainWindow)
        self.action31.setObjectName("action31")
        self.action32 = QtWidgets.QAction(mainWindow)
        self.action32.setObjectName("action32")
        self.action33 = QtWidgets.QAction(mainWindow)
        self.action33.setObjectName("action33")
        self.action34 = QtWidgets.QAction(mainWindow)
        self.action34.setObjectName("action34")
        self.action35 = QtWidgets.QAction(mainWindow)
        self.action35.setObjectName("action35")
        self.action41 = QtWidgets.QAction(mainWindow)
        self.action41.setObjectName("action41")
        self.action42 = QtWidgets.QAction(mainWindow)
        self.action42.setObjectName("action42")
        self.action43 = QtWidgets.QAction(mainWindow)
        self.action43.setObjectName("action43")
        self.action51 = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action51.setFont(font)
        self.action51.setObjectName("action51")
        self.action52 = QtWidgets.QAction(mainWindow)
        self.action52.setObjectName("action52")
        self.action53 = QtWidgets.QAction(mainWindow)
        self.action53.setObjectName("action53")
        self.action18 = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("tuandui8.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action18.setIcon(icon7)
        self.action18.setObjectName("action18")
        self.action19 = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("yeji.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action19.setIcon(icon8)
        self.action19.setObjectName("action19")
        self.action1A = QtWidgets.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("kufang6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action1A.setIcon(icon9)
        self.action1A.setObjectName("action1A")
        self.action1B = QtWidgets.QAction(mainWindow)
        self.action1B.setIcon(icon4)
        self.action1B.setObjectName("action1B")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "编辑窗口"))
        self.pushButton_4.setText(_translate("mainWindow", "下一条"))
        self.pushButton_5.setText(_translate("mainWindow", "退  出"))
        self.pushButton_1.setText(_translate("mainWindow", "保  存"))
        self.label_1.setText(_translate("mainWindow", "数据编辑："))
        self.pushButton_3.setText(_translate("mainWindow", "删  除"))
        self.label_2.setText(_translate("mainWindow", "唯一编码："))
        self.label_3.setText(_translate("mainWindow", "合同日期："))
        self.label_4.setText(_translate("mainWindow", "合同编号："))
        self.label_5.setText(_translate("mainWindow", "产品名称："))
        self.label_6.setText(_translate("mainWindow", "产品型号："))
        self.label_8.setText(_translate("mainWindow", "经 销 商："))
        self.label_7.setText(_translate("mainWindow", "生产厂商："))
        self.label_9.setText(_translate("mainWindow", "最终客户："))
        self.label_10.setText(_translate("mainWindow", "授 权 码："))
        self.label_11.setText(_translate("mainWindow", "授权到期："))
        self.label_12.setText(_translate("mainWindow", "存放地点："))
        self.label_13.setText(_translate("mainWindow", "状    态："))
        self.pushButton_2.setText(_translate("mainWindow", "新  増"))
        self.action11.setText(_translate("mainWindow", "合同管理"))
        self.action11.setShortcut(_translate("mainWindow", "Ctrl+C"))
        self.action12.setText(_translate("mainWindow", "资金管理"))
        self.action12.setShortcut(_translate("mainWindow", "Ctrl+M"))
        self.action13.setText(_translate("mainWindow", "产品管理"))
        self.action13.setShortcut(_translate("mainWindow", "Ctrl+P"))
        self.action14.setText(_translate("mainWindow", "进销管理"))
        self.action14.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.action15.setText(_translate("mainWindow", "渠道管理"))
        self.action15.setShortcut(_translate("mainWindow", "Ctrl+Q"))
        self.action16.setText(_translate("mainWindow", "客户管理"))
        self.action16.setShortcut(_translate("mainWindow", "Ctrl+Y"))
        self.action17.setText(_translate("mainWindow", "服务管理"))
        self.action17.setShortcut(_translate("mainWindow", "Ctrl+F"))
        self.action21.setText(_translate("mainWindow", "修改数据"))
        self.action22.setText(_translate("mainWindow", "插入数据"))
        self.action23.setText(_translate("mainWindow", "删除数据"))
        self.action24.setText(_translate("mainWindow", "更新数据"))
        self.action25.setText(_translate("mainWindow", "数据备份"))
        self.action26.setText(_translate("mainWindow", "数据恢复"))
        self.action31.setText(_translate("mainWindow", "保存为Excel"))
        self.action32.setText(_translate("mainWindow", "保存为Word"))
        self.action33.setText(_translate("mainWindow", "保存为Txt"))
        self.action34.setText(_translate("mainWindow", "保存为图片"))
        self.action35.setText(_translate("mainWindow", "打印报表"))
        self.action41.setText(_translate("mainWindow", "返回主页"))
        self.action42.setText(_translate("mainWindow", "退出系统"))
        self.action43.setText(_translate("mainWindow", "关闭电脑"))
        self.action51.setText(_translate("mainWindow", "帮助文档"))
        self.action52.setText(_translate("mainWindow", "版权声明"))
        self.action53.setText(_translate("mainWindow", "关于"))
        self.action18.setText(_translate("mainWindow", "人员管理"))
        self.action18.setShortcut(_translate("mainWindow", "Ctrl+R"))
        self.action19.setText(_translate("mainWindow", "业绩管理"))
        self.action19.setShortcut(_translate("mainWindow", "Ctrl+A"))
        self.action1A.setText(_translate("mainWindow", "仓储管理"))
        self.action1A.setShortcut(_translate("mainWindow", "Ctrl+K"))
        self.action1B.setText(_translate("mainWindow", "物流管理"))
        self.action1B.setShortcut(_translate("mainWindow", "Ctrl+W"))
