# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2900, 1260)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 1250))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1600, 1200))
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1, 90, 441, 531))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(450, -10, 1220, 1220))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_1.setMaximumSize(QtCore.QSize(300, 300))
        self.pushButton_1.setBaseSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_1.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_8.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_8.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_1.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_11.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_11.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_1.addWidget(self.pushButton_11, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_3.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_1.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_7.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_1.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_5.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_1.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_4.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_1.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_6.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_1.addWidget(self.pushButton_6, 1, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_9.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_1.addWidget(self.pushButton_9, 3, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_10.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_1.addWidget(self.pushButton_10, 3, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_12.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_1.addWidget(self.pushButton_12, 3, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(606, 606))
        self.pushButton_13.setMaximumSize(QtCore.QSize(600, 600))
        self.pushButton_13.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setIconSize(QtCore.QSize(600, 600))
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_1.addWidget(self.pushButton_13, 1, 1, 2, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(300, 300))
        self.pushButton_2.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_1.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 630, 441, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_c5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c5.setFont(font)
        self.pushButton_c5.setObjectName("pushButton_c5")
        self.gridLayout_2.addWidget(self.pushButton_c5, 8, 1, 1, 1)
        self.pushButton_c3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c3.setFont(font)
        self.pushButton_c3.setObjectName("pushButton_c3")
        self.gridLayout_2.addWidget(self.pushButton_c3, 9, 2, 1, 1)
        self.pushButton_c4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c4.setFont(font)
        self.pushButton_c4.setObjectName("pushButton_c4")
        self.gridLayout_2.addWidget(self.pushButton_c4, 8, 0, 1, 1)
        self.pushButton_c9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c9.setFont(font)
        self.pushButton_c9.setObjectName("pushButton_c9")
        self.gridLayout_2.addWidget(self.pushButton_c9, 7, 2, 1, 1)
        self.pushButton_c1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c1.setFont(font)
        self.pushButton_c1.setObjectName("pushButton_c1")
        self.gridLayout_2.addWidget(self.pushButton_c1, 9, 0, 1, 1)
        self.pushButton_ce = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ce.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ce.setFont(font)
        self.pushButton_ce.setObjectName("pushButton_ce")
        self.gridLayout_2.addWidget(self.pushButton_ce, 10, 3, 1, 1)
        self.pushButton_a = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_a.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a.setFont(font)
        self.pushButton_a.setObjectName("pushButton_a")
        self.gridLayout_2.addWidget(self.pushButton_a, 5, 3, 1, 1)
        self.pushButton_c8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c8.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c8.setFont(font)
        self.pushButton_c8.setObjectName("pushButton_c8")
        self.gridLayout_2.addWidget(self.pushButton_c8, 7, 1, 1, 1)
        self.pushButton_c7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c7.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c7.setFont(font)
        self.pushButton_c7.setObjectName("pushButton_c7")
        self.gridLayout_2.addWidget(self.pushButton_c7, 7, 0, 1, 1)
        self.pushButton_cc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cc.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cc.setFont(font)
        self.pushButton_cc.setObjectName("pushButton_cc")
        self.gridLayout_2.addWidget(self.pushButton_cc, 6, 3, 1, 1)
        self.lineEdit_c = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_c.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_c.setFont(font)
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.gridLayout_2.addWidget(self.lineEdit_c, 5, 0, 1, 3)
        self.pushButton_cx = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cx.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cx.setFont(font)
        self.pushButton_cx.setObjectName("pushButton_cx")
        self.gridLayout_2.addWidget(self.pushButton_cx, 7, 3, 1, 1)
        self.pushButton_cq = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cq.setFont(font)
        self.pushButton_cq.setObjectName("pushButton_cq")
        self.gridLayout_2.addWidget(self.pushButton_cq, 6, 0, 1, 1)
        self.pushButton_c6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c6.setFont(font)
        self.pushButton_c6.setObjectName("pushButton_c6")
        self.gridLayout_2.addWidget(self.pushButton_c6, 8, 2, 1, 1)
        self.pushButton_ca = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ca.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ca.setFont(font)
        self.pushButton_ca.setObjectName("pushButton_ca")
        self.gridLayout_2.addWidget(self.pushButton_ca, 8, 3, 1, 1)
        self.pushButton_cb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cb.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cb.setFont(font)
        self.pushButton_cb.setObjectName("pushButton_cb")
        self.gridLayout_2.addWidget(self.pushButton_cb, 6, 1, 1, 1)
        self.pushButton_c2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c2.setFont(font)
        self.pushButton_c2.setObjectName("pushButton_c2")
        self.gridLayout_2.addWidget(self.pushButton_c2, 9, 1, 1, 1)
        self.pushButton_cs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cs.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cs.setFont(font)
        self.pushButton_cs.setObjectName("pushButton_cs")
        self.gridLayout_2.addWidget(self.pushButton_cs, 6, 2, 1, 1)
        self.pushButton_cj = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cj.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cj.setFont(font)
        self.pushButton_cj.setObjectName("pushButton_cj")
        self.gridLayout_2.addWidget(self.pushButton_cj, 9, 3, 1, 1)
        self.lcdNumber_c = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_c.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lcdNumber_c.setAcceptDrops(False)
        self.lcdNumber_c.setAutoFillBackground(True)
        self.lcdNumber_c.setStyleSheet("color:rgb(0, 0, 255)")
        self.lcdNumber_c.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_c.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_c.setLineWidth(3)
        self.lcdNumber_c.setSmallDecimalPoint(False)
        self.lcdNumber_c.setDigitCount(12)
        self.lcdNumber_c.setProperty("value", 0.0)
        self.lcdNumber_c.setProperty("intValue", 0)
        self.lcdNumber_c.setObjectName("lcdNumber_c")
        self.gridLayout_2.addWidget(self.lcdNumber_c, 0, 0, 1, 4)
        self.pushButton_cd = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cd.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_cd.setObjectName("pushButton_cd")
        self.gridLayout_2.addWidget(self.pushButton_cd, 10, 2, 1, 1)
        self.pushButton_c0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_c0.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_c0.setFont(font)
        self.pushButton_c0.setObjectName("pushButton_c0")
        self.gridLayout_2.addWidget(self.pushButton_c0, 10, 0, 1, 2)
        self.textBrowser_c = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_c.sizePolicy().hasHeightForWidth())
        self.textBrowser_c.setSizePolicy(sizePolicy)
        self.textBrowser_c.setMaximumSize(QtCore.QSize(2555555, 120))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_c.setFont(font)
        self.textBrowser_c.setAutoFillBackground(False)
        self.textBrowser_c.setObjectName("textBrowser_c")
        self.gridLayout_2.addWidget(self.textBrowser_c, 2, 0, 1, 4)
        self.lcdNumber_date = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_date.setGeometry(QtCore.QRect(1, 0, 441, 80))
        self.lcdNumber_date.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lcdNumber_date.setAcceptDrops(False)
        self.lcdNumber_date.setAutoFillBackground(True)
        self.lcdNumber_date.setStyleSheet("color:rgb(0,0, 255)")
        self.lcdNumber_date.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_date.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_date.setLineWidth(3)
        self.lcdNumber_date.setSmallDecimalPoint(False)
        self.lcdNumber_date.setDigitCount(10)
        self.lcdNumber_date.setProperty("value", 0.0)
        self.lcdNumber_date.setProperty("intValue", 0)
        self.lcdNumber_date.setObjectName("lcdNumber_date")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(1677, 90, 381, 1121))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setLineWidth(3)
        self.textEdit.setObjectName("textEdit")
        self.lcdNumber_time = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_time.setGeometry(QtCore.QRect(1677, 0, 381, 80))
        self.lcdNumber_time.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lcdNumber_time.setAcceptDrops(False)
        self.lcdNumber_time.setAutoFillBackground(True)
        self.lcdNumber_time.setStyleSheet("color:rgb(0,0, 255)")
        self.lcdNumber_time.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_time.setLineWidth(3)
        self.lcdNumber_time.setSmallDecimalPoint(False)
        self.lcdNumber_time.setDigitCount(10)
        self.lcdNumber_time.setProperty("value", 0.0)
        self.lcdNumber_time.setProperty("intValue", 0)
        self.lcdNumber_time.setObjectName("lcdNumber_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"合同管理"))
        self.pushButton_8.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"业绩管理"))
        self.pushButton_11.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"物流管理"))
        self.pushButton_3.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"资金管理"))
        self.pushButton_7.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"渠道管理"))
        self.pushButton_5.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"进销管理"))
        self.pushButton_4.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"服务管理"))
        self.pushButton_6.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"人员管理"))
        self.pushButton_9.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"客户管理"))
        self.pushButton_10.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"仓储管理"))
        self.pushButton_12.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"参数设置"))
        self.pushButton_13.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"\n"
"销售管理系统"))
        self.pushButton_2.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"产品管理"))
        self.pushButton_c5.setText(_translate("MainWindow", "5"))
        self.pushButton_c3.setText(_translate("MainWindow", "3"))
        self.pushButton_c4.setText(_translate("MainWindow", "4"))
        self.pushButton_c9.setText(_translate("MainWindow", "9"))
        self.pushButton_c1.setText(_translate("MainWindow", "1"))
        self.pushButton_ce.setText(_translate("MainWindow", "＝"))
        self.pushButton_a.setText(_translate("MainWindow", "Clear"))
        self.pushButton_c8.setText(_translate("MainWindow", "8"))
        self.pushButton_c7.setText(_translate("MainWindow", "7"))
        self.pushButton_cc.setText(_translate("MainWindow", "÷"))
        self.pushButton_cx.setText(_translate("MainWindow", "×"))
        self.pushButton_cq.setText(_translate("MainWindow", "退出"))
        self.pushButton_c6.setText(_translate("MainWindow", "6"))
        self.pushButton_ca.setText(_translate("MainWindow", "＋"))
        self.pushButton_cb.setText(_translate("MainWindow", "退格"))
        self.pushButton_c2.setText(_translate("MainWindow", "2"))
        self.pushButton_cs.setText(_translate("MainWindow", "清除"))
        self.pushButton_cj.setText(_translate("MainWindow", "－"))
        self.pushButton_cd.setText(_translate("MainWindow", "."))
        self.pushButton_c0.setText(_translate("MainWindow", "0"))
